# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  server:
    image: server
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - 5215:5215
  database:
    image: devtodolistdb
    build:
      context: database
      dockerfile: ./Dockerfile
    ports:
      - 1433:1433
  frontend:
    image: frontend
    build:
      context: frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5173:5173
