name: Release CD

on:
  workflow_call: 
  workflow_dispatch:

permissions:
  contents: write
  security-events: write
  id-token: write

jobs:
  api-deploy:
    name: API Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{secrets.AWS_ASSUME_ROLE}}
        aws-region: "eu-west-1"
        role-session-name: GitHub_to_AWS_via_FederatedOIDC

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Publish API
      working-directory: ./server
      run: dotnet publish -c Release --output ../bundle/api

    - name: Create ZIP Package
      working-directory: ./bundle/api
      run: |
        zip -r deploy_package.zip .

    - name: Upload API Package
      working-directory: ./bundle/api
      run: aws s3 cp deploy_package.zip s3://958933916692-deploy-bucket

    - name: Create New API Version
      run: aws elasticbeanstalk create-application-version --application-name api-app --source-bundle S3Bucket="958933916692-deploy-bucket",S3Key="deploy_package.zip" --version-label "deploy-${{ github.sha }}" --description "commit-sha-${{ github.sha }}"

    - name: Deploy API
      run: aws elasticbeanstalk update-environment --environment-name api-env --version-label "deploy-${{ github.sha }}"
