name: Deploy CI

on:
  workflow_call: 

permissions:
  contents: read
  security-events: write
  id-token: write

jobs:
  api-ci:
    name: API CI
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build API
      working-directory: ./server
      run: dotnet build